apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MarcFont16/lab04-application-personal.git'
    targetRevision: HEAD
    # Com que el 'deploy' el tens a l'arrel, apuntem directament aquí:
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true