# deploy/charts/my-secure-app/values.yaml

frontend:
  replicaCount: 1
  image:
    repository: lab2g02registry.azurecr.io/lab04/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: lab2g02registry.azurecr.io/lab04/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

imagePullSecrets: 
  - name: acr-secret # Recorda crear aquest secret al namespace lab04-app

cluster:
  enabled: true
  type: postgresql
  mode: standalone
  version:
    postgresql: "16"
  cluster:
    enableSuperuserAccess: true
    initdb:
      database: taskdb
  monitoring:
    enabled: false
  instances: 1
  annotations:
    helm.sh/resource-policy: keep
  backups:
    enabled: false