apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: private-config-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  encryptedData:
    password: "placeholder"
    username: "MarcFont16"
    url: "https://github.com/MarcFont16/lab04-config-personal.git"