apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-secure-app
  namespace: lab03-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: lab03-app-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - g02.cpo2026.it
      secretName: my-secure-app-tls
  rules:
    - host: g02.cpo2026.it
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-secure-app-app-chart-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-secure-app-app-chart-frontend
                port:
                  number: 80